# Generated by Django 6.0.5 on 2026-07-11 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='partida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='partidas.partida'),
            preserve_default=False,
        ),
    ]
