# Generated by Django 6.0.5 on 2026-06-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.IntegerField(unique=True)),
                ('time_1', models.CharField(max_length=100)),
                ('time_2', models.CharField(max_length=100)),
                ('placar_1', models.IntegerField(blank=True, null=True)),
                ('placar_2', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('NI', 'Não iniciada'), ('EA', 'Em andamento'), ('FI', 'Finalizada'), ('AD', 'Adiada'), ('CA', 'Cancelada')], default='NI', max_length=2, verbose_name='Status')),
                ('tempo', models.CharField(blank=True, max_length=10, null=True)),
                ('fase', models.CharField(max_length=50)),
                ('estatisticas_finais', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
