# Generated by Django 6.0.5 on 2026-07-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='rodada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='tempo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
