# Generated by Django 6.0.5 on 2026-07-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0002_partida_rodada_alter_partida_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='rodada',
        ),
    ]
