# Generated by Django 6.0.5 on 2026-07-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0003_remove_rodada'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='time_1_imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='time_2_imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
