# Generated by Django 6.0.5 on 2026-07-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nome',
            new_name='apelido',
        ),
    ]
