# Generated by Django 6.0.5 on 2026-07-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_amizade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_atividade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
