# Generated by Django 6.0.5 on 2026-06-17 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('IN', 'Iniciado'), ('FI', 'Finalizado')], default='IN', max_length=2, verbose_name='Status')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boloes', to='partidas.partida')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='boloes', to=settings.AUTH_USER_MODEL)),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boloes_vencidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_1', models.IntegerField()),
                ('placar_2', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('bolao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to='bolao.bolao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(blank=True, null=True)),
                ('valor_pontuacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('palpite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='bolao.palpite')),
            ],
        ),
    ]
