# Generated by Django 6.0.5 on 2026-07-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palpite',
            name='pontuacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='palpite',
            name='valor_pontuacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Pontuacao',
        ),
    ]
