# Generated by Django 6.0.5 on 2026-07-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0002_palpite_pontuacao_palpite_valor_pontuacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolao',
            options={'verbose_name': 'Bolão', 'verbose_name_plural': 'Bolões'},
        ),
        migrations.AlterModelOptions(
            name='palpite',
            options={'verbose_name': 'Palpite', 'verbose_name_plural': 'Palpites'},
        ),
        migrations.AlterField(
            model_name='bolao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
