# Generated by Django 6.0.5 on 2026-07-09 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0003_alter_bolao_options_alter_palpite_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bolao',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boloes_criados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
