# Generated by Django 6.0.5 on 2026-07-11 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0004_bolao_dono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palpite',
            old_name='usuario',
            new_name='dono',
        ),
        migrations.AlterField(
            model_name='palpite',
            name='placar_1',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'O valor do placar não pode ser inferior a 0'), django.core.validators.MaxValueValidator(99, 'O valor do placar não pode ser superior a 99')]),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='placar_2',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'O valor do placar não pode ser inferior a 0'), django.core.validators.MaxValueValidator(99, 'O valor do placar não pode ser superior a 99')]),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, 'O valor do palpite não pode ser inferior a 1')]),
        ),
    ]
