# Generated by Django 6.0.5 on 2026-07-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0005_rename_usuario_palpite_dono_alter_palpite_placar_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolao',
            name='status',
            field=models.CharField(choices=[('AB', 'Aberto'), ('FI', 'Finalizado')], default='AB', max_length=2, verbose_name='Status'),
        ),
    ]
