# Generated by Django 6.0.5 on 2026-07-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0006_alter_bolao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palpite',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='palpite',
            name='valor_pontuacao',
        ),
    ]
